# Generated by Django 5.2.7 on 2025-12-20 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_a_job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job Post', 'verbose_name_plural': 'Job Posts'},
        ),
        migrations.AlterModelTable(
            name='jobpost',
            table='job_post',
        ),
    ]
