# Generated by Django 5.2.7 on 2025-12-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_a_job', '0002_alter_jobpost_options_alter_jobpost_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='employer',
            new_name='user',
        ),
    ]
