# Generated by Django 5.2.7 on 2025-12-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_a_job', '0003_rename_employer_jobpost_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='user',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='user_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
