# Generated by Django 5.2.7 on 2025-12-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_a_job', '0004_remove_jobpost_user_jobpost_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
