# Generated by Django 5.2.7 on 2025-12-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_a_job', '0005_alter_jobpost_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='benefits',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
