# Generated by Django 5.2.7 on 2025-12-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_a_job', '0006_jobpost_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
