# Generated by Django 5.2.7 on 2026-02-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_a_job', '0007_alter_jobpost_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
