# Generated by Django 5.2.7 on 2026-02-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_a_job', '0009_alter_jobpost_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
