# Generated by Django 5.2.7 on 2026-01-10 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perksbenefits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perksbenefits',
            name='user_id',
        ),
        migrations.AddField(
            model_name='perksbenefits',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='perks_benefits', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
