# Generated by Django 5.2.7 on 2026-01-29 05:40

import django.db.models.deletion
import job_seeker_documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('documents', models.FileField(blank=True, null=True, upload_to=job_seeker_documents.models.upload_document_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Seeker Document',
                'verbose_name_plural': 'Job Seeker Document',
                'db_table': 'applicant_document',
                'ordering': ['-created_at'],
            },
        ),
    ]
