# Generated by Django 5.2.7 on 2026-01-20 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post_a_job', '0007_alter_jobpost_benefits'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('user_ids', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='post_a_job.jobpost')),
            ],
            options={
                'verbose_name': 'Job Apply',
                'verbose_name_plural': 'Job Apply',
                'db_table': 'job_apply',
                'ordering': ['-created_at'],
            },
        ),
    ]
