# Generated by Django 5.2.7 on 2026-01-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_apply', '0002_remove_jobapply_user_ids_jobapply_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapply',
            name='job_post',
        ),
        migrations.AddField(
            model_name='jobapply',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
