# Generated by Django 5.2.7 on 2026-01-23 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_apply', '0003_remove_jobapply_job_post_jobapply_status'),
        ('post_a_job', '0007_alter_jobpost_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='job_post',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='post_a_job.jobpost'),
            preserve_default=False,
        ),
    ]
