# Generated by Django 5.2.7 on 2026-01-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_apply', '0004_jobapply_job_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='employer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
