# Generated by Django 5.2.7 on 2026-01-20 15:34

import django.db.models.deletion
import my_resume.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('resume_info', models.JSONField()),
                ('resume', models.ImageField(blank=True, null=True, upload_to=my_resume.models.upload_resume_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'My Resume',
                'verbose_name_plural': 'My Resume',
                'db_table': 'my_resume',
                'ordering': ['-created_at'],
            },
        ),
    ]
