# Generated by Django 5.2.7 on 2026-01-21 00:15

import my_resume.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_resume', '0002_alter_myresume_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myresume',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=my_resume.models.upload_resume_path),
        ),
    ]
