# Generated by Django 5.2.7 on 2026-01-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_rename_is_verified_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='expires_at',
        ),
    ]
